language: java
jdk:
    - oraclejdk8
arch:
  - arm64
os:
  - linux
services:
  - docker
branches:
  only:
    - master
before_install:
  - docker login -u "$DOCKER_USERNAME" -p $DOCKER_PASSWORD 
script: 
  - cd rocketmq-console 
  - mvn clean package -Dmaven.test.skip=true docker:build
