language: java
arch:
  - arm64
os:
  - linux
services:
  - docker
branches:
  only:
    - master
before_install:
  - docker login -u "$DOCKER_USERNAME" -p $DOCKER_PASSWORD
  - sudo apt-get -y install maven
script: 
  - cd rocketmq-console 
  - mvn clean package -Dmaven.test.skip=true
  - cp src/main/docker/Dockerfile target/
  - cd target
  - docker build -t toyangdon/rocketmq-console:4.5.0 .
  - docker push toyangdon/rocketmq-console:4.5.0
